#+TITLE:  Zhserver - Haskell Web Server for Zotero Database 
#+AUTHOR: Caio Rodrigues 
#+EMAIL:  <caiorss.rodrigues@gmail.com>

* Documentation 
** Overview 

Zhserver is an application server that provides a json REST API to
interface Zotero database and allows multiple users and third party
apps to search documents by collections, tags, author and so on. 

Basic functionality:

 - Query the database by
   - Collection
   - Tag
   - Author
   - Document ID
   - Download Zotero files. 

** Benefits 

Find, classify information, books, magazines, laws, patents, technical
standards, web page snapshots and papers fast. 

** Road map 

 - [] Find items by tag
 - [] Find items by ID
 - [x] Find items by collection
 - [x] Find items by author
 - [] Find items by a group of authors
 - [] Improve design for mobile devices
 - [] Transfer the database from SQLite to Postgres SQL
 - [] Add the nix file to the project.
 - [] Add logging to the server.
 - [] Improve Front End
 - [] Improve User Interface Functionality
 - [] Improve User Interface Design 
 - [] Add tag search
 - [] Create JavaScript functions to create templates.
 - [] Add the database documentation
 - [] Implement a filter
 - [] Implement browser history
 - [] Implement user friendly URL 

** REST API doc

The API has the following scheme:

| URL Route               | Description                                       |   |
|-------------------------+---------------------------------------------------+---|
| =/api=                  | Display the API documentation                     |   |
| =/api/colls=            | Returns all collections names and collections IDs |   |
| =/api/coll?id=20=       | Returns all items from collection which ID is 20  |   |
| =/api/item?id=10=       | Return the item which ID is 10                    |   |
| =/api/attachment?id=20= | Return a link to file of item  which ID is 10     |   |
|                         |                                                   |   |





* Database Documentation 
** Search Titles that contains a word 

Search all titles that contains the string "functional".

#+BEGIN_SRC sql 
SELECT itemData.itemID, itemDataValues.value  
FROM   itemData, itemDataValues, itemAttachments
WHERE  fieldID = 110 
AND    itemData.valueID = itemDataValues.valueID
AND    itemAttachments.sourceItemID = itemData.itemID
AND    itemDataValues.value LIKE "%functional%" 
#+END_SRC


#+BEGIN_SRC sql 
sqlite> 
sqlite> SELECT itemData.itemID, itemDataValues.value  
   ...> FROM   itemData, itemDataValues, itemAttachments
   ...> WHERE  fieldID = 110 
   ...> AND    itemData.valueID = itemDataValues.valueID
   ...> AND    itemAttachments.sourceItemID = itemData.itemID
   ...> AND    itemDataValues.value LIKE "%functional%" 
   ...> ;
1936|Functional Programming
2688|Currently struggling. Can someone help em transition from functional programming to using OOP? : learnpython
2750|When to use functional programming languages and techniques - TechRepublic
2752|Where functional programming fits in - TechRepublic
2754|Commercial Uses: Going functional on exotic trades
2772|Functional Programming in the Financial Industry | Open Parallel
2794|An introduction to functional programming
2798|functional programming | Math ∩ Programming
...
#+END_SRC
** Search by a Regex Pattern 

#+BEGIN_SRC sql 
SELECT itemData.itemID, itemDataValues.value  
FROM   itemData, itemDataValues, itemAttachments
WHERE  fieldID = 110 
AND    itemData.valueID = itemDataValues.valueID
AND    itemAttachments.sourceItemID = itemData.itemID
AND    itemDataValues.value REGEXP "math.*" 
#+END_SRC

Result: 

#+BEGIN_SRC sql 
"2987"	"Functional Patterns for the non-mathematician"
"4842"	"Power of mathematics: Reasoning about functional types"
"6094"	"Discrete mathematics using a computer"
#+END_SRC
